env:
  browser: true
  node: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
settings:
  react:
    version: detect
globals:
  ga: readonly
  React: readonly
  DocumentTouch: readonly
rules:
  no-unused-vars: 1
  react/display-name: 0
  react/prop-types: 0
