export const REQUEST_FEATURED_POSTS_LIST = 'REQUEST_FEATURED_POSTS_LIST';
export const RECEIVE_FEATURED_POSTS_LIST = 'RECEIVE_FEATURED_POSTS_LIST';
export const RECEIVE_FEATURED_POSTS_ERROR = 'RECEIVE_FEATURED_POSTS_ERROR';

export const REQUEST_RESOURCE = 'REQUEST_RESOURCE';
export const RECEIVE_RESOURCE = 'RECEIVE_RESOURCE';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';

export const REQUEST_PAGE = 'REQUEST_PAGE';
export const RECEIVE_PAGE = 'RECEIVE_PAGE';
export const RECEIVE_PAGE_ERROR = 'RECEIVE_PAGE_ERROR';

export const REQUEST_POST = 'REQUEST_POST';
export const RECEIVE_POST = 'RECEIVE_POST';
export const RECEIVE_POST_ERROR = 'RECEIVE_POST_ERROR';
